### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by lxxue** [seravee08/Hierarchical-Link-Selection-for-Disambiguation-#1]
Hi,

Thanks for the work and sharing the code. I wonder if there is a Linux version as in the paper the runtime is reported on a Linux machine?

**Comment by seravee08** [comment]
Hello Lixin,

Thanks for your interest in our work. Unfortunately, we don't have a Linux
version at this time. The results in the paper are reported from a windows
machine.

Thanks,
Fan
